# Generated by Django 3.0.6 on 2020-05-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200522_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Embed',
        ),
    ]
